version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/lifetime
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "71:ee:4a:8e:be:5f:01:1f:47:9a:4b:1f:82:1a:90:73"
      - run: scp -o StrictHostKeyChecking=no -r ~/lifetime  ubuntu@95.213.37.8:/home/ubuntu
      - run: ssh -o StrictHostKeyChecking=no ubuntu@95.213.37.8 sudo cp /home/ubuntu/lifetime/devops/lifetime.service /etc/systemd/system/
#      - run: ssh -o StrictHostKeyChecking=no  sudo systemctl stop graphicone-dev
#      - run: ssh -o StrictHostKeyChecking=n sudo systemctl start graphicone-dev
#      - run: ssh -o StrictHostKeyChecking=no sudo systemctl is-active --quiet graphicone-dev
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
